export const networkAvailable = [
  {
    id: 1,
    image: "/chains/ethereum.svg",
    name: "Goerli",
    chain: 5,
    status: "live",
  },
  {
    id: 2,
    image: "/chains/bnb_yellow.svg",
    name: "Binance Testnet",
    chain: 97,
    status: "live",
  },
  {
    id: 3,
    image: "/chains/avalanche.svg",
    name: "Avalanche Fuji",
    chain: 43113,
    status: "live",
  },
  {
    id: 4,
    image: "/chains/polygon_1.svg",
    name: "Polygon Mumbai",
    chain: 80001,
    status: "live",
  },
  {
    id: 8,
    image: "/chains/ethereum.svg",
    name: "Sepolia",
    chain: 11155111,
    status: "live",
  },
  {
    id: 9,
    image: "/chains/blast.svg",
    name: "Blast Sepolia",
    chain: 168587773,
    status: "live",
  },
  // {
  //   id: 5,
  //   image: "/chains/klaytn.svg",
  //   name: "Klaytn Mainnet",
  //   chain: 8217,
  //   status: "soon",
  // },
  // {
  //   id: 6,
  //   image: "/chains/fantom.svg",
  //   name: "Fantom Opera",
  //   chain: 250,
  //   status: "soon",
  // },
  // {
  //   id: 7,
  //   image: "/chains/gnosis.svg",
  //   name: "Gnosis",
  //   chain: 100,
  //   status: "soon",
  // },
];
