import { Inter } from "next/font/google";
import "./globals.css";
import { headers } from "next/headers";
import { Web3Modal } from "@/context/Web3Modal";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Lets Mint",
  description: "Generated by Ethena Nova",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {" "}
        <Web3Modal>{children}</Web3Modal>
      </body>
    </html>
  );
}
